using System.Runtime.Versioning;
using System.Text;
using CORCleanup.Core.Interfaces;
using CORCleanup.Core.Models;

namespace CORCleanup.Core.Services.Tools;

/// <summary>
/// Generates a COR Intelligence branded HTML system summary report.
/// Gathers data from all hardware, software, network, and admin services in parallel,
/// then renders a professional, print-friendly HTML document.
/// </summary>
[SupportedOSPlatform("windows")]
public sealed class ReportService : IReportService
{
    private readonly ISystemInfoService _systemInfo;
    private readonly ISoftwareInventoryService _softwareInventory;
    private readonly INetworkInfoService _networkInfo;
    private readonly IStartupService _startupService;
    private readonly IAntivirusService _antivirusService;

    public ReportService(
        ISystemInfoService systemInfo,
        ISoftwareInventoryService softwareInventory,
        INetworkInfoService networkInfo,
        IStartupService startupService,
        IAntivirusService antivirusService)
    {
        _systemInfo = systemInfo;
        _softwareInventory = softwareInventory;
        _networkInfo = networkInfo;
        _startupService = startupService;
        _antivirusService = antivirusService;
    }

    public async Task<string> GenerateHtmlReportAsync(CancellationToken ct = default)
    {
        // Gather all data in parallel — each task isolated with try/catch
        SystemInfo? sysInfo = null;
        RamSummary? ramSummary = null;
        List<DiskHealthInfo> diskHealth = [];
        BatteryInfo? battery = null;
        List<NetworkAdapterInfo> adapters = [];
        List<StartupEntry> startupItems = [];
        List<SoftwareEntry> software = [];
        List<AntivirusProduct> avProducts = [];

        var tasks = new List<Task>
        {
            Task.Run(async () =>
            {
                try { sysInfo = await _systemInfo.GetSystemInfoAsync(); }
                catch { /* Service unavailable — section will show placeholder */ }
            }, ct),

            Task.Run(async () =>
            {
                try { ramSummary = await _systemInfo.GetRamSummaryAsync(); }
                catch { }
            }, ct),

            Task.Run(async () =>
            {
                try { diskHealth = await _systemInfo.GetDiskHealthAsync(); }
                catch { }
            }, ct),

            Task.Run(async () =>
            {
                try { battery = await _systemInfo.GetBatteryInfoAsync(); }
                catch { }
            }, ct),

            Task.Run(async () =>
            {
                try { adapters = await _networkInfo.GetAdaptersAsync(); }
                catch { }
            }, ct),

            Task.Run(async () =>
            {
                try { startupItems = await _startupService.GetStartupItemsAsync(); }
                catch { }
            }, ct),

            Task.Run(async () =>
            {
                try { software = await _softwareInventory.GetInstalledSoftwareAsync(); }
                catch { }
            }, ct),

            Task.Run(async () =>
            {
                try { avProducts = await _antivirusService.ScanAsync(); }
                catch { }
            }, ct)
        };

        await Task.WhenAll(tasks);

        // Build the HTML report
        var html = new StringBuilder(32_768);
        var timestamp = DateTime.Now.ToString("dd/MM/yyyy HH:mm");
        var machineName = sysInfo?.ComputerName ?? Environment.MachineName;

        html.AppendLine("<!DOCTYPE html>");
        html.AppendLine("<html lang=\"en\">");
        html.AppendLine("<head>");
        html.AppendLine("<meta charset=\"UTF-8\">");
        html.AppendLine("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
        html.AppendLine($"<title>System Summary Report — {Encode(machineName)}</title>");
        AppendStyles(html);
        html.AppendLine("</head>");
        html.AppendLine("<body>");

        // Header
        AppendHeader(html, machineName, timestamp);

        // Sections
        AppendSystemInfoSection(html, sysInfo);
        AppendHardwareSection(html, sysInfo, ramSummary);
        AppendDiskHealthSection(html, diskHealth);
        AppendBatterySection(html, battery);
        AppendNetworkSection(html, adapters);
        AppendStartupSection(html, startupItems);
        AppendSoftwareSection(html, software);
        AppendAntivirusSection(html, avProducts);

        // Footer
        html.AppendLine("<div class=\"footer\">");
        html.AppendLine($"<p>Report generated by <strong>COR Cleanup v1.0.17</strong> on {Encode(timestamp)}</p>");
        html.AppendLine("<p>COR Intelligence &mdash; COR Solutions Services Ltd</p>");
        html.AppendLine("</div>");

        html.AppendLine("</body>");
        html.AppendLine("</html>");

        return html.ToString();
    }

    public async Task SaveReportAsync(string htmlContent, string filePath, CancellationToken ct = default)
    {
        var directory = Path.GetDirectoryName(filePath);
        if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
            Directory.CreateDirectory(directory);

        await File.WriteAllTextAsync(filePath, htmlContent, Encoding.UTF8, ct);
    }

    // ================================================================
    // HTML Section Builders
    // ================================================================

    private static void AppendHeader(StringBuilder html, string machineName, string timestamp)
    {
        html.AppendLine("<div class=\"header\">");
        html.AppendLine("<div class=\"header-content\">");
        html.AppendLine("<div class=\"brand\">");
        html.AppendLine("<h1>COR Intelligence</h1>");
        html.AppendLine("<span class=\"tagline\">System Summary Report</span>");
        html.AppendLine("</div>");
        html.AppendLine("<div class=\"meta\">");
        html.AppendLine($"<p><strong>Machine:</strong> {Encode(machineName)}</p>");
        html.AppendLine($"<p><strong>Generated:</strong> {Encode(timestamp)}</p>");
        html.AppendLine("</div>");
        html.AppendLine("</div>");
        html.AppendLine("</div>");
    }

    private static void AppendSystemInfoSection(StringBuilder html, SystemInfo? info)
    {
        html.AppendLine("<div class=\"section\">");
        html.AppendLine("<h2>System Information</h2>");

        if (info is null)
        {
            html.AppendLine("<p class=\"no-data\">System information could not be retrieved.</p>");
            html.AppendLine("</div>");
            return;
        }

        html.AppendLine("<table>");
        AppendRow(html, "Computer Name", info.ComputerName);
        AppendRow(html, "Operating System", info.OsEdition);
        AppendRow(html, "OS Version", info.OsVersion);
        AppendRow(html, "OS Build", info.OsBuild);
        AppendRow(html, "Install Date", info.InstallDate.ToString("dd/MM/yyyy"));
        AppendRow(html, "Edition Type", info.Edition.ToString());
        html.AppendLine("</table>");
        html.AppendLine("</div>");
    }

    private static void AppendHardwareSection(StringBuilder html, SystemInfo? info, RamSummary? ram)
    {
        html.AppendLine("<div class=\"section\">");
        html.AppendLine("<h2>Hardware</h2>");

        if (info is null && ram is null)
        {
            html.AppendLine("<p class=\"no-data\">Hardware information could not be retrieved.</p>");
            html.AppendLine("</div>");
            return;
        }

        if (info is not null)
        {
            html.AppendLine("<h3>Processor</h3>");
            html.AppendLine("<table>");
            AppendRow(html, "CPU", info.CpuName);
            AppendRow(html, "Cores / Threads", $"{info.CpuCores} / {info.CpuThreads}");
            AppendRow(html, "Max Clock", $"{info.CpuMaxClockMhz} MHz");
            html.AppendLine("</table>");

            html.AppendLine("<h3>Graphics</h3>");
            html.AppendLine("<table>");
            AppendRow(html, "GPU", info.GpuName);
            AppendRow(html, "Driver Version", info.GpuDriverVersion);
            AppendRow(html, "VRAM", info.GpuVramFormatted);
            html.AppendLine("</table>");

            html.AppendLine("<h3>Motherboard</h3>");
            html.AppendLine("<table>");
            AppendRow(html, "Manufacturer", info.MotherboardManufacturer);
            AppendRow(html, "Product", info.MotherboardProduct);
            AppendRow(html, "BIOS Version", info.BiosVersion);
            AppendRow(html, "BIOS Date", info.BiosDate);
            html.AppendLine("</table>");
        }

        if (ram is not null)
        {
            html.AppendLine("<h3>Memory (RAM)</h3>");
            html.AppendLine("<table>");
            AppendRow(html, "Installed", ram.InstalledFormatted);
            AppendRow(html, "Maximum Supported", ram.MaxCapacityFormatted);
            AppendRow(html, "Slots", $"{ram.UsedSlots} of {ram.TotalSlots} used ({ram.EmptySlots} empty)");
            AppendRow(html, "Channel Configuration", ram.ChannelConfig);
            html.AppendLine("</table>");

            if (ram.Dimms.Count > 0)
            {
                html.AppendLine("<h4>DIMM Slots</h4>");
                html.AppendLine("<table class=\"full-width\">");
                html.AppendLine("<thead><tr>");
                html.AppendLine("<th>Slot</th><th>Capacity</th><th>Speed</th><th>Type</th><th>Manufacturer</th><th>Part Number</th>");
                html.AppendLine("</tr></thead>");
                html.AppendLine("<tbody>");
                foreach (var dimm in ram.Dimms)
                {
                    html.AppendLine("<tr>");
                    html.AppendLine($"<td>{Encode(dimm.SlotLabel)}</td>");
                    html.AppendLine($"<td>{Encode(dimm.CapacityFormatted)}</td>");
                    html.AppendLine($"<td>{dimm.SpeedMhz} MHz</td>");
                    html.AppendLine($"<td>{Encode(dimm.MemoryType)}{(dimm.IsEcc ? " (ECC)" : "")}</td>");
                    html.AppendLine($"<td>{Encode(dimm.Manufacturer)}</td>");
                    html.AppendLine($"<td>{Encode(dimm.PartNumber)}</td>");
                    html.AppendLine("</tr>");
                }
                html.AppendLine("</tbody></table>");
            }
        }

        html.AppendLine("</div>");
    }

    private static void AppendDiskHealthSection(StringBuilder html, List<DiskHealthInfo> disks)
    {
        html.AppendLine("<div class=\"section\">");
        html.AppendLine("<h2>Disk Health</h2>");

        if (disks.Count == 0)
        {
            html.AppendLine("<p class=\"no-data\">Disk health data could not be retrieved.</p>");
            html.AppendLine("</div>");
            return;
        }

        html.AppendLine("<table class=\"full-width\">");
        html.AppendLine("<thead><tr>");
        html.AppendLine("<th>Model</th><th>Size</th><th>Type</th><th>Health</th><th>Temperature</th><th>Power-On Hours</th><th>Reallocated Sectors</th>");
        html.AppendLine("</tr></thead>");
        html.AppendLine("<tbody>");

        foreach (var disk in disks)
        {
            var healthClass = disk.OverallHealth switch
            {
                DiskHealthStatus.Good => "health-good",
                DiskHealthStatus.Caution => "health-caution",
                DiskHealthStatus.Bad => "health-bad",
                _ => "health-unknown"
            };

            html.AppendLine("<tr>");
            html.AppendLine($"<td>{Encode(disk.Model)}</td>");
            html.AppendLine($"<td>{Encode(disk.SizeFormatted)}</td>");
            html.AppendLine($"<td>{Encode(disk.TypeSummary)}</td>");
            html.AppendLine($"<td class=\"{healthClass}\">{Encode(disk.HealthDisplay)}</td>");
            html.AppendLine($"<td>{Encode(disk.TemperatureDisplay)}</td>");
            html.AppendLine($"<td>{(disk.PowerOnHours.HasValue ? $"{disk.PowerOnHours:N0} hrs" : "\u2014")}</td>");
            html.AppendLine($"<td>{(disk.ReallocatedSectors.HasValue ? disk.ReallocatedSectors.Value.ToString() : "\u2014")}</td>");
            html.AppendLine("</tr>");
        }

        html.AppendLine("</tbody></table>");
        html.AppendLine("</div>");
    }

    private static void AppendBatterySection(StringBuilder html, BatteryInfo? battery)
    {
        html.AppendLine("<div class=\"section\">");
        html.AppendLine("<h2>Battery Health</h2>");

        if (battery is null || !battery.HasBattery)
        {
            html.AppendLine("<p class=\"no-data\">No battery detected (desktop system).</p>");
            html.AppendLine("</div>");
            return;
        }

        var healthClass = battery.NeedsReplacement ? "health-bad" : "health-good";

        html.AppendLine("<table>");
        AppendRow(html, "Health", $"<span class=\"{healthClass}\">{battery.HealthPercent:F1}%</span>{(battery.NeedsReplacement ? " — Replacement recommended" : "")}");
        AppendRow(html, "Design Capacity", battery.DesignCapacityFormatted);
        AppendRow(html, "Full Charge Capacity", battery.FullChargeFormatted);
        AppendRow(html, "Cycle Count", battery.CycleCount.ToString());
        AppendRow(html, "Chemistry", battery.Chemistry);
        AppendRow(html, "Manufacturer", battery.Manufacturer);
        AppendRow(html, "Current Charge", $"{battery.ChargePercent}%{(battery.IsCharging ? " (charging)" : "")}");
        html.AppendLine("</table>");
        html.AppendLine("</div>");
    }

    private static void AppendNetworkSection(StringBuilder html, List<NetworkAdapterInfo> adapters)
    {
        html.AppendLine("<div class=\"section\">");
        html.AppendLine("<h2>Network Adapters</h2>");

        if (adapters.Count == 0)
        {
            html.AppendLine("<p class=\"no-data\">No network adapters found.</p>");
            html.AppendLine("</div>");
            return;
        }

        html.AppendLine("<table class=\"full-width\">");
        html.AppendLine("<thead><tr>");
        html.AppendLine("<th>Name</th><th>Type</th><th>Status</th><th>IP Address</th><th>Gateway</th><th>DNS</th><th>MAC Address</th><th>Speed</th>");
        html.AppendLine("</tr></thead>");
        html.AppendLine("<tbody>");

        foreach (var adapter in adapters)
        {
            html.AppendLine("<tr>");
            html.AppendLine($"<td>{Encode(adapter.Name)}</td>");
            html.AppendLine($"<td>{Encode(adapter.Type)}</td>");
            html.AppendLine($"<td>{Encode(adapter.Status)}</td>");
            html.AppendLine($"<td>{Encode(adapter.IpAddress ?? "\u2014")}</td>");
            html.AppendLine($"<td>{Encode(adapter.Gateway ?? "\u2014")}</td>");
            html.AppendLine($"<td>{Encode(adapter.DnsDisplay)}</td>");
            html.AppendLine($"<td>{Encode(adapter.MacAddress ?? "\u2014")}</td>");
            html.AppendLine($"<td>{Encode(adapter.SpeedDisplay)}</td>");
            html.AppendLine("</tr>");
        }

        html.AppendLine("</tbody></table>");
        html.AppendLine("</div>");
    }

    private static void AppendStartupSection(StringBuilder html, List<StartupEntry> items)
    {
        html.AppendLine("<div class=\"section\">");
        html.AppendLine("<h2>Startup Items</h2>");

        if (items.Count == 0)
        {
            html.AppendLine("<p class=\"no-data\">No startup items found.</p>");
            html.AppendLine("</div>");
            return;
        }

        var thirdParty = items.Where(i => !i.IsMicrosoft).ToList();

        html.AppendLine($"<p>{items.Count} total startup item(s), {thirdParty.Count} third-party</p>");
        html.AppendLine("<table class=\"full-width\">");
        html.AppendLine("<thead><tr>");
        html.AppendLine("<th>Enabled</th><th>Name</th><th>Publisher</th><th>Source</th><th>Impact</th><th>Signed</th>");
        html.AppendLine("</tr></thead>");
        html.AppendLine("<tbody>");

        foreach (var item in items)
        {
            html.AppendLine("<tr>");
            html.AppendLine($"<td>{(item.IsEnabled ? "Yes" : "No")}</td>");
            html.AppendLine($"<td>{Encode(item.Name)}</td>");
            html.AppendLine($"<td>{Encode(item.Publisher ?? "\u2014")}</td>");
            html.AppendLine($"<td>{item.Source}</td>");
            html.AppendLine($"<td>{item.Impact}</td>");
            html.AppendLine($"<td>{(item.IsSigned ? "Yes" : "No")}</td>");
            html.AppendLine("</tr>");
        }

        html.AppendLine("</tbody></table>");
        html.AppendLine("</div>");
    }

    private static void AppendSoftwareSection(StringBuilder html, List<SoftwareEntry> software)
    {
        html.AppendLine("<div class=\"section\">");
        html.AppendLine("<h2>Software Inventory</h2>");

        if (software.Count == 0)
        {
            html.AppendLine("<p class=\"no-data\">No installed software found.</p>");
            html.AppendLine("</div>");
            return;
        }

        html.AppendLine($"<p>{software.Count} program(s) installed</p>");
        html.AppendLine("<table class=\"full-width\">");
        html.AppendLine("<thead><tr>");
        html.AppendLine("<th>Name</th><th>Publisher</th><th>Version</th><th>Installed</th><th>Size</th>");
        html.AppendLine("</tr></thead>");
        html.AppendLine("<tbody>");

        foreach (var entry in software.OrderBy(s => s.DisplayName, StringComparer.OrdinalIgnoreCase))
        {
            html.AppendLine("<tr>");
            html.AppendLine($"<td>{Encode(entry.DisplayName)}</td>");
            html.AppendLine($"<td>{Encode(entry.Publisher ?? "\u2014")}</td>");
            html.AppendLine($"<td>{Encode(entry.DisplayVersion ?? "\u2014")}</td>");
            html.AppendLine($"<td>{Encode(entry.InstallDateFormatted)}</td>");
            html.AppendLine($"<td>{Encode(entry.SizeFormatted)}</td>");
            html.AppendLine("</tr>");
        }

        html.AppendLine("</tbody></table>");
        html.AppendLine("</div>");
    }

    private static void AppendAntivirusSection(StringBuilder html, List<AntivirusProduct> products)
    {
        html.AppendLine("<div class=\"section\">");
        html.AppendLine("<h2>Antivirus Status</h2>");

        if (products.Count == 0)
        {
            html.AppendLine("<p class=\"no-data\">No antivirus products detected.</p>");
            html.AppendLine("</div>");
            return;
        }

        html.AppendLine("<table class=\"full-width\">");
        html.AppendLine("<thead><tr>");
        html.AppendLine("<th>Product</th><th>Status</th><th>Enabled</th><th>Up to Date</th><th>Version</th><th>Remnants</th>");
        html.AppendLine("</tr></thead>");
        html.AppendLine("<tbody>");

        foreach (var av in products)
        {
            html.AppendLine("<tr>");
            html.AppendLine($"<td>{Encode(av.ProductName)}</td>");
            html.AppendLine($"<td style=\"color:{av.StatusColour};font-weight:600\">{Encode(av.StatusDisplay)}</td>");
            html.AppendLine($"<td>{av.EnabledDisplay}</td>");
            html.AppendLine($"<td>{av.UpToDateDisplay}</td>");
            html.AppendLine($"<td>{Encode(av.Version ?? "\u2014")}</td>");
            html.AppendLine($"<td>{Encode(av.RemnantSummary)}</td>");
            html.AppendLine("</tr>");
        }

        html.AppendLine("</tbody></table>");
        html.AppendLine("</div>");
    }

    // ================================================================
    // Helpers
    // ================================================================

    private static void AppendRow(StringBuilder html, string label, string value)
    {
        html.AppendLine($"<tr><td class=\"label\">{Encode(label)}</td><td>{value}</td></tr>");
    }

    private static string Encode(string value)
    {
        return System.Net.WebUtility.HtmlEncode(value);
    }

    // ================================================================
    // CSS Styles
    // ================================================================

    private static void AppendStyles(StringBuilder html)
    {
        html.AppendLine("<style>");
        html.AppendLine(@"
            :root {
                --bg-primary: #1a1a2e;
                --bg-secondary: #16213e;
                --bg-card: #1e2a45;
                --accent: #06B6D4;
                --accent-light: #22d3ee;
                --text-primary: #e2e8f0;
                --text-secondary: #94a3b8;
                --border: #334155;
                --health-good: #22c55e;
                --health-caution: #f59e0b;
                --health-bad: #ef4444;
                --health-unknown: #94a3b8;
            }

            * {
                margin: 0;
                padding: 0;
                box-sizing: border-box;
            }

            body {
                font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;
                background: var(--bg-primary);
                color: var(--text-primary);
                line-height: 1.6;
                font-size: 14px;
            }

            .header {
                background: linear-gradient(135deg, var(--bg-secondary), var(--bg-primary));
                border-bottom: 3px solid var(--accent);
                padding: 32px 40px;
            }

            .header-content {
                display: flex;
                justify-content: space-between;
                align-items: flex-end;
                max-width: 1200px;
                margin: 0 auto;
            }

            .brand h1 {
                font-size: 28px;
                font-weight: 700;
                color: var(--accent);
                letter-spacing: 0.5px;
            }

            .brand .tagline {
                display: block;
                font-size: 16px;
                color: var(--text-secondary);
                margin-top: 4px;
            }

            .meta {
                text-align: right;
                color: var(--text-secondary);
                font-size: 13px;
            }

            .meta p { margin: 2px 0; }

            .section {
                max-width: 1200px;
                margin: 24px auto;
                padding: 0 40px;
            }

            h2 {
                font-size: 20px;
                font-weight: 600;
                color: var(--accent);
                border-bottom: 2px solid var(--border);
                padding-bottom: 8px;
                margin-bottom: 16px;
            }

            h3 {
                font-size: 16px;
                font-weight: 600;
                color: var(--text-primary);
                margin: 16px 0 8px 0;
            }

            h4 {
                font-size: 14px;
                font-weight: 600;
                color: var(--text-secondary);
                margin: 12px 0 8px 0;
            }

            p {
                margin-bottom: 12px;
                color: var(--text-secondary);
            }

            .no-data {
                font-style: italic;
                color: var(--text-secondary);
                padding: 12px 0;
            }

            table {
                width: 100%;
                border-collapse: collapse;
                margin-bottom: 16px;
                background: var(--bg-card);
                border-radius: 8px;
                overflow: hidden;
            }

            thead {
                background: var(--bg-secondary);
            }

            th {
                text-align: left;
                padding: 10px 14px;
                font-weight: 600;
                font-size: 12px;
                text-transform: uppercase;
                letter-spacing: 0.5px;
                color: var(--accent-light);
                border-bottom: 2px solid var(--border);
            }

            td {
                padding: 8px 14px;
                border-bottom: 1px solid var(--border);
                vertical-align: top;
            }

            tr:last-child td {
                border-bottom: none;
            }

            tbody tr:hover {
                background: rgba(6, 182, 212, 0.05);
            }

            td.label {
                font-weight: 600;
                color: var(--text-secondary);
                width: 220px;
                white-space: nowrap;
            }

            .full-width {
                width: 100%;
            }

            .health-good { color: var(--health-good); font-weight: 600; }
            .health-caution { color: var(--health-caution); font-weight: 600; }
            .health-bad { color: var(--health-bad); font-weight: 600; }
            .health-unknown { color: var(--health-unknown); font-weight: 600; }

            .footer {
                max-width: 1200px;
                margin: 40px auto 24px auto;
                padding: 20px 40px;
                border-top: 2px solid var(--border);
                text-align: centre;
                color: var(--text-secondary);
                font-size: 12px;
            }

            .footer p {
                margin: 4px 0;
                color: var(--text-secondary);
            }

            /* Print styles */
            @media print {
                :root {
                    --bg-primary: #ffffff;
                    --bg-secondary: #f8fafc;
                    --bg-card: #ffffff;
                    --accent: #0891b2;
                    --accent-light: #0891b2;
                    --text-primary: #1e293b;
                    --text-secondary: #475569;
                    --border: #cbd5e1;
                    --health-good: #16a34a;
                    --health-caution: #d97706;
                    --health-bad: #dc2626;
                    --health-unknown: #6b7280;
                }

                body {
                    background: white;
                    color: #1e293b;
                    font-size: 11px;
                }

                .header {
                    background: white;
                    border-bottom: 3px solid var(--accent);
                    padding: 16px 20px;
                    -webkit-print-color-adjust: exact;
                    print-color-adjust: exact;
                }

                .brand h1 {
                    font-size: 22px;
                }

                .section {
                    padding: 0 20px;
                    margin: 12px auto;
                    page-break-inside: avoid;
                }

                table {
                    background: white;
                    border: 1px solid var(--border);
                }

                thead {
                    background: #f1f5f9;
                    -webkit-print-color-adjust: exact;
                    print-color-adjust: exact;
                }

                th {
                    color: #0891b2;
                    border-bottom: 2px solid #cbd5e1;
                }

                td {
                    border-bottom: 1px solid #e2e8f0;
                }

                tbody tr:hover {
                    background: none;
                }

                .footer {
                    padding: 12px 20px;
                    margin-top: 24px;
                }
            }
        ");
        html.AppendLine("</style>");
    }
}
